import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Create a function to simulate the spread of a disease
def simulate_disease(population_size, infection_rate, recovery_rate, days):
    # Create a list to store the number of susceptible, infected, and recovered individuals
    SIR = np.zeros((3, days))
    # Initialize the number of susceptible, infected, and recovered individuals
    SIR[0, 0] = population_size
    SIR[1, 0] = 1
    SIR[2, 0] = 0
    # Simulate the spread of the disease for day in range(1, days):
    for day in range(1, days):
        # Calculate the number of new infections
        new_infections = SIR[0, day-1] * infection_rate
        # Calculate the number of recoveries
        recoveries = SIR[1, day-1] * recovery_rate
        # Update the number of susceptible, infected, and recovered individuals
        SIR[0, day] = SIR[0, day-1] - new_infections
        SIR[1, day] = SIR[1, day-1] + new_infections - recoveries
        SIR[2, day] = SIR[2, day-1] + recoveries
    # Return the number of susceptible, infected, and recovered individuals
    return SIR
# Simulate the spread of the disease
SIR = simulate_disease(1000, 0.1, 0.05, 100)
# Plot the number of susceptible, infected, and recovered individuals
plt.plot(SIR[0, :], label="Susceptible")
plt.plot(SIR[1, :], label="Infected")
plt.plot(SIR[2, :], label="Recovered")
plt.legend()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
# Load the data
data = pd.read_csv('human_behavior.csv')
# Explore the data
print(data.head())
print(data.describe())
# Create a scatter plot of the data
sns.scatterplot(x="x", y="y", data=data)
plt.show()
# Create a linear regression model
model = LinearRegression()
# Fit the model to the data
model.fit(data'x', data['y'])
# Print the model coefficients
print(model.coef_)
print(model.intercept_)
# Make predictions
predictions = model.predict(data'x')
# Plot the predictions
sns.scatterplot(x="x", y="y", data=data)
sns.lineplot(x="x", y="y", data=predictions)
plt.show()
# Evaluate the model
print(mean_squared_error(data['y'], predictions))
# Create an interface for the user to input data
def get_user_input():
    x = float(input("Enter a value for x: "))
    return x
# Make a prediction based on the user input
def make_prediction(x):
    prediction = model.predict(x)
    return prediction
# Print the prediction
def print_prediction(prediction):
    print(f"The predicted value for y is {prediction}.")
# Run the program
if __name__ == "__main__":
    x = get_user_input()
    prediction = make_prediction(x)
    print_prediction(prediction)

import pandas as pdimport
numpy as npimport 
matplotlib.pyplot as pltimport 
seaborn as sns
# Load the datadata = pd.read_csv('human_behavior.csv')
# Explore the dataprint(data.head())print(data.describe())
# Create a scatter plot of the datasns.scatterplot(x="x", y="y", data=data)plt.show()
# Create a linear regression modelmodel = LinearRegression()
# Fit the model to the datamodel.fit(data'x', data['y'])
# Print the model coefficientsprint(model.coef_)print(model.intercept_)
# Make predictionspredictions = model.predict(data'x')
# Plot the predictionssns.scatterplot(x="x", y="y", data=data)sns.lineplot(x="x", y="y", data=predictions)plt.show()
# Evaluate the modelprint(mean_squared_error(data['y'], predictions))​


import cv2
import numpy as np
# Load the Haar Cascade classifier for detecting faces
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
# Define a function to detect faces in an image
def detect_faces(image):
    # Convert the image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    # Detect faces in the image
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    # Draw a rectangle around each face
    for (x, y, w, h) in faces:
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)
    return image
# Define a function to track faces in a video
def track_faces(video):
    # Create a VideoCapture object
    cap = cv2.VideoCapture(video)
    # Loop over the frames in the video
    while True:
        # Read the next frame
        ret, frame = cap.read()
        # If the frame is empty, break out of the loop
        if not ret:
            break
        # Detect faces in the frame
        frame = detect_faces(frame)
        # Display the frame
        cv2.imshow('Faces', frame)
        # Wait for a key press
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    # Release the VideoCapture object
    cap.release()
    # Destroy all windows
    cv2.destroyAllWindows()
# Start the face tracking program
track_faces('video.mp4')


import cv2
import numpy as np
# Load the Haar Cascade classifier for detecting faces
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
# Define a function to detect faces in an image
def detect_faces(image):
    # Convert the image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    # Detect faces in the image
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    # Draw a rectangle around each face
    for (x, y, w, h) in faces:
        cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)
    return image
# Define a function to track faces in a video
def track_faces(video):
    # Create a VideoCapture object
    cap = cv2.VideoCapture(video)
    # Loop over the frames in the video
    while True:
        # Read the next frame
        ret, frame = cap.read()
        # If the frame is empty, break out of the loop
        if not ret:
            break
        # Detect faces in the frame
        frame = detect_faces(frame)
        # Display the frame
        cv2.imshow('Faces', frame)
        # Wait for a key press
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    # Release the VideoCapture object
    cap.release()
    # Destroy all windows
    cv2.destroyAllWindows()
# Start the face tracking program
track_faces('video.mp4')




    
